version: '3.8'

services:
  stocks-backend:
    build:
      context: ./backend/python-stocks
      dockerfile: Dockerfile
    container_name: today-stocks-backend
    expose:
      - "8020"  # Only expose to internal network
    environment:
      - TZ=UTC
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-today.techbrohomelab.xyz}  # Add your domain here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - default
      - shared-web
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: today-frontend
    expose:
      - "80"
    environment:
      - VITE_BACKEND_URL=/api
      - VITE_API_MODE=${VITE_API_MODE:-real}
    depends_on:
      stocks-backend:
        condition: service_healthy
    networks:
      - default
      - shared-web
    restart: unless-stopped

networks:
  default:
    name: today-network
    driver: bridge
  shared-web:
    external: true
    name: shared-web
