version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: today-nginx
    volumes:
      - ./nginx-host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Expose to Cloudflare Tunnel
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: today-backend
    expose:
      - "8020"  # Only expose to internal network
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: today-frontend
    expose:
      - "80"  # Only expose to internal network
    environment:
      - VITE_BACKEND_URL=/api
      - VITE_API_MODE=${VITE_API_MODE:-real}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: today-network
    driver: bridge
