services:
  caddy:
    image: caddy:2-alpine
    container_name: shared-caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./error:/usr/share/caddy/error:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"  # Caddy handles HTTPS automatically
    networks:
      - shared-web
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  shared-web:
    name: shared-web
    driver: bridge
